export const tableFeature = {
    "columnData":[
        {
            "columnName":"",
            "columnWidth":"10%",
            "style":{},
            "className":"",
            "icon":"",
        },
        {
            "columnName":"Order ID",
            "columnWidth":"12%",
            "style":{},
            "className":"",
            "icon":"",
        },
        {
            "columnName":"Customer",
            "columnWidth":"20%",
            "style":{},
            "className":"",
            "icon":"",
        },
        {
            "columnName":"Status",
            "columnWidth":"20%",
            "style":{},
            "className":"",
            "icon":"",
        },
        {
            "columnName":"Items",
            "columnWidth":"20%",
            "style":{},
            "className":"",
            "icon":"",
        },
        {
            "columnName":"Amount",
            "columnWidth":"20%",
            "style":{},
            "className":"",
            "icon":"",
        },
        {
            "columnName":"Payment",
            "columnWidth":"20%",
            "style":{},
            "className":"",
            "icon":"",
        },
        {
            "columnName":"Fulfillment",
            "columnWidth":"20%",
            "style":{},
            "className":"",
            "icon":"",
        },
        {
            "columnName":"Actions",
            "columnWidth":"20%",
            "style":{},
            "className":"",
            "icon":"",
        },
    ]
}